### ISSUE TITLE
Add Processors

### ISSUE THREAD

**Issue by KGRC199913** [KGRC199913/BatchRenameMaterial#9]
+ Uppercase from x to y (if y > length => y = length)
+ Lowercase from x to y (if y > length => y = length)
+ Regex Uppercase + Regex Lowercase (Uppercase/Lowercase All token match the regex)
+ Change token position base on regex (let user choose the regex + position).
+ Trim string (remove all leading + trailing white space)
+ Name normalize (Trim + Uppercase first character of each word (let user choose word separator) + Left only 1 word separator)
+ Create GUID

**Comment by DilVika** [comment]
6/7 Processors were added.
